<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="application" nsURI="org.sheepy.lily.core.model.application"
    nsPrefix="application">
  <eClassifiers xsi:type="ecore:EClass" name="Application" eSuperTypes="root.ecore#//LObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="views" upperBound="-1"
        eType="#//IView" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="engines" upperBound="-1"
        eType="#//IEngine" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="run" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fullscreen" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resizeable" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="headless" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        defaultValueLiteral="Vulkan Application"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" unique="false" eType="ecore:EDataType types.ecore#//Vector2i"
        defaultValueLiteral="400,400"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentView" eType="#//IView"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cadenceInHz" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
        defaultValueLiteral="60"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cadence" eType="#//ICadence"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IEngine" abstract="true" interface="true"
      eSuperTypes="root.ecore#//LObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="IView" abstract="true" interface="true"
      eSuperTypes="root.ecore#//LObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="ICadence" abstract="true" interface="true"/>
</ecore:EPackage>
