<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="application" nsURI="org.sheepy.lily.core.model.application"
    nsPrefix="application">
  <eClassifiers xsi:type="ecore:EClass" name="Application">
    <eStructuralFeatures xsi:type="ecore:EReference" name="engines" upperBound="-1"
        eType="#//IEngine" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="run" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="Vulkan Application"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scene" eType="#//Scene"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="timeConfiguration" eType="#//TimeConfiguration"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extensionPkg" eType="#//ApplicationExtensionPkg"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IApplicationExtension" abstract="true"
      interface="true" eSuperTypes="types.ecore#//LNamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ApplicationExtensionPkg">
    <eStructuralFeatures xsi:type="ecore:EReference" name="extensions" upperBound="-1"
        eType="#//IApplicationExtension" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimeConfiguration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeStep" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong" defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" lowerBound="1" eType="ecore:EEnum types.ecore#//ETimeUnit"
        defaultValueLiteral="SECONDS"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeFactor" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IEngine" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IScenePart" abstract="true" interface="true"
      eSuperTypes="inference.ecore#//IInferenceObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="ICadence" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Scene">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parts" upperBound="-1"
        eType="#//IScenePart" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fullscreen" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resizeable" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" unique="false" eType="ecore:EDataType types.ecore#//Vector2i"
        defaultValueLiteral="400,400"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenericScenePart" eSuperTypes="#//IScenePart types.ecore#//LNamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BackgroundImage" eSuperTypes="types.ecore#//LNamedElement #//IScenePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="resource" eType="#//IResource"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="clearColor" lowerBound="1"
        eType="ecore:EDataType types.ecore#//Vector3i" defaultValueLiteral="0;0;0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sampling" lowerBound="1"
        eType="#//ESampling"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ESampling">
    <eLiterals name="Linear"/>
    <eLiterals name="Nearest" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourcePkg">
    <eStructuralFeatures xsi:type="ecore:EReference" name="resources" upperBound="-1"
        eType="#//IResource" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IResource" eSuperTypes="types.ecore#//LNamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="VirtualResource" eSuperTypes="#//IResource"/>
  <eClassifiers xsi:type="ecore:EClass" name="FileResource" abstract="true" eSuperTypes="#//IResource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalResource" eSuperTypes="#//FileResource"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractModuleResource" abstract="true"
      eSuperTypes="#//FileResource"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModuleResource" eSuperTypes="#//AbstractModuleResource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="module" lowerBound="1"
        eType="ecore:EDataType types.ecore#//JavaModule"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringModuleResource" eSuperTypes="#//AbstractModuleResource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="moduleName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
