<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="presentation" nsURI="org.sheepy.lily.core.model.presentation"
    nsPrefix="presentation">
  <eClassifiers xsi:type="ecore:EClass" name="IPositionElement" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="position" unique="false"
        eType="ecore:EDataType types.ecore#//Vector2i" defaultValueLiteral="0;0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="verticalRelative" unique="false"
        eType="ecore:EEnum types.ecore#//EVerticalRelative" defaultValueLiteral="TOP"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="horizontalRelative" unique="false"
        eType="ecore:EEnum types.ecore#//EHorizontalRelative" defaultValueLiteral="LEFT"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ISizedElement" abstract="true" interface="true"
      eSuperTypes="#//IPositionElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UI" abstract="true" interface="true"
      eSuperTypes="application.ecore#//IScenePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="uiPages" upperBound="-1"
        eType="#//UIPage" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentUIPage" eType="#//UIPage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IUIElement" abstract="true" interface="true"
      eSuperTypes="inference.ecore#//IInferenceObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="UIPage" eSuperTypes="#//ISizedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="panels" upperBound="-1"
        eType="#//IPanel" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IPanel" abstract="true" interface="true"
      eSuperTypes="types.ecore#//LNamedElement #//IUIElement #//IPositionElement"/>
</ecore:EPackage>
