<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ui" nsURI="org.sheepy.lily.core.model.ui" nsPrefix="ui">
  <eClassifiers xsi:type="ecore:EClass" name="Panel" eSuperTypes="presentation.ecore#//IPanel presentation.ecore#//ISizedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="controls" upperBound="-1"
        eType="#//IControl" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="showTitle" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minimizable" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="movable" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minimized" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IControl" abstract="true" interface="true"
      eSuperTypes="presentation.ecore#//IUIElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Widget" abstract="true" interface="true"
      eSuperTypes="#//IControl presentation.ecore#//IUIElement presentation.ecore#//ISizedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractLabel" abstract="true" eSuperTypes="#//Widget">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fontScale" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EFloat"
        defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DynamicRowLayout" eSuperTypes="#//IControl">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
        defaultValueLiteral="16"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="columnCount" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
        defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableLabel" eSuperTypes="#//AbstractLabel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variableResolver" lowerBound="1"
        eType="ecore:EClass variable.ecore#//IVariableResolver" containment="true"
        resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="showName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="format" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Label" eSuperTypes="#//AbstractLabel"/>
  <eClassifiers xsi:type="ecore:EClass" name="Slider" eSuperTypes="#//Widget">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minValue" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxValue" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
        defaultValueLiteral="10"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="step" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variableResolver" lowerBound="1"
        eType="ecore:EClass variable.ecore#//IVariableResolver" containment="true"
        resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TextField" eSuperTypes="#//Widget">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variableResolver" eType="ecore:EClass variable.ecore#//IVariableResolver"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractButton" abstract="true" eSuperTypes="#//Widget">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Button" eSuperTypes="#//AbstractButton">
    <eOperations name="lActions" unique="false" eType="ecore:EDataType action.ecore#//ActionList">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return this.getActions();"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getExecutor" unique="false" eType="ecore:EClass root.ecore#//LObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="&lt;%org.sheepy.lily.core.model.root.LObject%> unit = this;&#xA;while (((unit instanceof &lt;%org.sheepy.lily.core.model.application.IView%>) == false))&#xA;{&#xA;&#x9;unit = unit.lParent();&#xA;}&#xA;return unit;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shortcut" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" unique="false" eType="ecore:EEnum types.ecore#//EKeyState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="ecore:EClass action.ecore#//Action" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractBooleanButton" abstract="true"
      eSuperTypes="#//AbstractButton">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="textWhenTrue" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="textWhenFalse" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanButton" eSuperTypes="#//AbstractBooleanButton">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variableResolver" eType="ecore:EClass variable.ecore#//IVariableResolver"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanActionButton" eSuperTypes="#//AbstractBooleanButton">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actionWhenTrue" eType="ecore:EClass action.ecore#//Action"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actionWhenFalse" eType="ecore:EClass action.ecore#//Action"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
</ecore:EPackage>
